"""v1

Revision ID: 9d6bd609487e
Revises: 
Create Date: 2023-03-25 13:19:42.896425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d6bd609487e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ngp_audits',
    sa.Column('audit_id', sa.Integer(), nullable=False),
    sa.Column('audit_dag_id', sa.String(length=50), nullable=False),
    sa.Column('audit_task_id', sa.String(length=50), nullable=False),
    sa.Column('audit_run_id', sa.String(length=50), nullable=False),
    sa.Column('audit_record_time', sa.DateTime(), nullable=False),
    sa.Column('audit_job_start_time', sa.DateTime(), nullable=False),
    sa.Column('audit_job_status', sa.String(length=10), nullable=False),
    sa.Column('audit_detail', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('audit_id')
    )
    op.create_table('ngp_job',
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('job_dag_id', sa.String(length=50), nullable=False),
    sa.Column('job_task_id', sa.String(length=50), nullable=False),
    sa.Column('job_run_id', sa.String(length=50), nullable=False),
    sa.Column('job_status', sa.String(length=10), nullable=False),
    sa.Column('job_detail', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('job_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ngp_job')
    op.drop_table('ngp_audits')
    # ### end Alembic commands ###
